### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by pennpeng** [paascloud/paascloud-master#55]
```
Could not resolve dependencies for project com.liuzm.paascloud.provider:paascloud-provider-omc:jar:1.0: The following artifacts could not be resolved: com.alipay:alipay-sdk-java:jar:20170725114550, com.alipay:alipay-trade-sdk:jar:20161215: Could not find artifact com.alipay:alipay-sdk-java:jar:20170725114550 in nexus (http://maven.aliyun.com/nexus/content/groups/public/)
```

**Comment by paascloud** [comment]
配置一下免费提供给大家的私服

**Comment by pennpeng** [comment]
多谢

**Comment by liudican** [comment]
您好！我也报这个错误，请问在哪里配置私服呢？谢谢

**Comment by liudican** [comment]
您好！我配置了这个，但是又报错了！Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.5.13.RELEASE from/to nexus-passcloud (http://139.199.125.217:8081/content/repositories/): Authentication failed for http://139.199.125.217:8081/content/repositories/org/springframework/boot/spring-boot-starter-parent/1.5.13.RELEASE/spring-boot-starter-parent-1.5.13.RELEASE.pom 401 Unauthorized
请问这是啥意思？谢谢 
<mirror>
      <id>nexus-passcloud</id>
      <mirrorOf>*</mirrorOf>
      <name>nexus passcloud</name>
      <url>http://139.199.125.217:8081/content/repositories/</url>
    </mirror>
