### ISSUE TITLE
关于jwt的问题

### ISSUE THREAD

**Issue by windyrjc** [paascloud/paascloud-master#6]
请问一下你对于jwt是怎么使用的,怎么解决jwt的单设备登录问题的

**Comment by paascloud** [comment]
使用jwt一个最难解决的问题就是令牌桶的设计，令牌的管理，在paascloud中我简单实现了令牌的管理，每个令牌的默认是2个小时，这里采用了redis和数据库同时落地的方法，同时提供了页面管理在线用户的操作，提供了踢出用户的接口（暂时没有实现），这里简单讲一下思路，可以在网关中取redis或者数据库的令牌，如果禁用的令牌不予提供接口服务，变向的禁用jwt token，同时数据库提供每个用户的jwt token的树，提供jwt token的监控服务，比如刷新token，单点问题其实可以结合自己的业务，比如jwt 树中已有未过期的用户，如果用户强制登录则踢出上一次登录的token。

**Comment by paascloud** [comment]
这个问题关闭了，如果还有问题再创建新的issues吧
