### ISSUE TITLE
熬了两晚上，环境终于搭好了。说一些注意事项：

### ISSUE THREAD

**Issue by ghost** [paascloud/paascloud-master#64]
![snipaste_20190101_044313](https://user-images.githubusercontent.com/26244337/50567444-d827b780-0d7f-11e9-944e-95ead6bfeda7.jpg)

- 1、多看看大佬的博客。里面讲解的很全了。或者看[文档手册](https://document.paascloud.net/),配置直接clone这个[仓库](https://github.com/paascloud/paascloud-config-repo.git)
- 2、服务器先尽量在win上，确保每一个都要启动。
  - redis需要设置密码：paascloud@redis， 
  - nginx 必须在cmd中启动，不要点nginx.exe.没有效果的去任务管理器看看。关于配置[看这里]（）
  - rocketmq不要安装太高版本，找不到class时需要在runbroker.cmd配置中 添加双引号"JAVA_OPT=%JAVA_OPT% -cp "%CLASSPATH%""
  - SwitchHosts!.exe这个软件必须要管理员启动,最好在cmd中刷新下dns， ipconfig /flushdns
- 3、关于paascloud-admin-web自行在github上搜索，都开源了也不差一个后端，估计是版权的原因。在根路径下npm install 、npm run build  、npm run dev. 
  - 如果安装了nginx，配置了以下.需要在项目的config/index.js中修改端口
```
    server {
        listen       80;
        server_name  dev-admin.paascloud.net;
        location / {
            proxy_pass http://localhost:7020;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
```
- 4、感谢大佬，感谢开源。接下来就是看具体的业务逻辑。debug模式走起...

**Comment by lurker8** [comment]
redis在哪儿配的了?

**Comment by xiaofanjun** [comment]
你是在一台机器上跑起来的吗
