### ISSUE TITLE
elastic-job-lite-starter和elastic-job-lite-spring对比都做了哪些封装，无法下载封装后的依赖

### ISSUE THREAD

**Issue by kinbod** [paascloud/paascloud-master#7]
elastic-job-lite-starter和elastic-job-lite-spring对比都做了哪些封装，无法下载封装后的依赖

**Comment by paascloud** [comment]
抽了一些常用参数，和两个抽象方法，详见https://github.com/paascloud/elastic-job-lite-starter-master
