### ISSUE TITLE
jar包无法下载的来看这里

### ISSUE THREAD

**Issue by paascloud** [paascloud/paascloud-master#9]
考虑到大家急迫的心情，在这里个人向大家提供一台为期一个月的maven私服地址，使用方法见[博客](http://paascloud.net/2018/03/26/springcloud/nexus/maven-nexus-use/   )：http://paascloud.net/2018/03/26/springcloud/nexus/maven-nexus-use/   

这个私服库大家一起来维护，如果有jar包无法下载，请回复对应的jar包版本，例如：
```
<dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>17.0</version>
 </dependency>

```

我们会在第一时间维护私服库 如果觉得这个项目对您有所帮助请推荐给身边的朋友，谢谢大家的理解和支持

**Comment by hai0378** [comment]
给力，终于可以继续安装了

**Comment by liuyingying** [comment]
大哥，私服不能访问了啊！！！

**Comment by ada223ada** [comment]
只提供一个月？ 

 http://nexus.paascloud.net
 已经失效了。。。

**Comment by paascloud** [comment]
加群吧  群里有心的配置 这段时间比较忙我没有更新

2018-05-08 13:35 GMT+08:00 ada223ada <notifications@github.com>:

**Comment by wjm0729** [comment]
大哥 地址404啊

**Comment by songqipan888** [comment]
> 考虑到大家急迫的心情，在这里个人向大家提供一台为期一个月的maven私服地址，使用方法见[博客](http://paascloud.net/2018/03/26/springcloud/nexus/maven-nexus-use/)：http://paascloud.net/2018/03/26/springcloud/nexus/maven-nexus-use/
> 
> 这个私服库大家一起来维护，如果有jar包无法下载，请回复对应的jar包版本，例如：
> 
> ```
> <dependency>
>         <groupId>com.google.guava</groupId>
>         <artifactId>guava</artifactId>
>         <version>17.0</version>
>  </dependency>
> ```
> 我们会在第一时间维护私服库 如果觉得这个项目对您有所帮助请推荐给身边的朋友，谢谢大家的理解和支持

<dependency>
            <groupId>com.alipay</groupId>
            <artifactId>alipay-trade-sdk</artifactId>
            <version>20161215</version>
        </dependency>
这个包不能下载，能给发一个吗
